### PR TITLE
Call schema.default with DitoContext

### PR DESCRIPTION
**Pull request by puckey**
Call the `default` property of the component schemas with DitoContext when it is a function

### CODE REVIEW

**Comment by lehni** [comment]
@puckey this is trickier than I thought, actually… The problem is that when `default` is called, the `form`, `view` or even type component doesn't always exist yet. For example, it is used to create the initial data for a newly created item, see the use of `setDefaults()` in the code. Other scenarios are nested data that is edited through nested forms, these aren't always initiated immediately, only when you visit them, yet the defaults have to be set right away for newly created data. So at the time when `default()` is called, the components may not exist at all… And the way `DitoContext` is handled so far, it's really bound to components.

Could you outline your use-case for this feature a bit more, so I can see what I can suggest? I am currently thinking we should do the opposite, and not even support a callback here…

**Comment by puckey** [comment]
Hmmm good point.. I was looking to use it in a component context. For example, this is a multiselect that gets its initial value through `default: ({ item }) => item?.place?.countryId,`.

```js
countryId: {
  label: 'Country',
  type: 'multiselect',
  width: '25%',
  placeholder: 'select country',
  multiple: false,
  searchable: true,
  exclude: true,
  default: ({ item }) => item?.place?.countryId,
  options: {
    async data({ request }) {
      return request<LocationCountry[]>({
        url: 'countries'
      });
    },
    label: 'title',
    value: 'id'
  }
},
```

**Comment by lehni** [comment]
I understand the use case, but it's tricky to allow this pattern in a clean way…

My suggestion would be to use `compute` instead. It's a little more compliated with`compute()` since you need to use the already set value if it exists and fall back on reading the value from item if not, but it reads quite well, generally. The difference to `default` is that `compute` only gets called when the component is instantiated or when the reactive data that you use in it changes.

```js
countryId: {
  label: 'Country',
  type: 'multiselect',
  width: '25%',
  placeholder: 'select country',
  multiple: false,
  searchable: true,
  exclude: true,
  compute: ({ value: countryId, item }) => countryId ?? item?.place?.countryId,
  options: {
    async data({ request }) {
      return request<LocationCountry[]>({
        url: 'countries'
      });
    },
    label: 'title',
    value: 'id'
  }
}
```

**Comment by puckey** [comment]
I was using `format` in that way, but it felt wrong semantically  – `compute` is much better - thanks!

**Pull request closed without merging**
